### ISSUE TITLE
JavaScript Capstone project: Webpack and Kanban Setup

### ISSUE THREAD

**Issue by amare1990** [amare1990/JavaScript-Capstone-Project#21]
- We setup the webpack and Kanban.
- We are two coding partners in number.

**Comment by sonyco-4u** [comment]
Amare my coding partner is student (A)
while me Anthony  is student (B)

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @amare1990 and @sonyco-4u, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Aspects to improve ♻️

- [ ] I see that you added issues for each card of the project, but you should copy [this template](https://github.com/microverseinc/curriculum-javascript/projects/1) following the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in the projects section of this repository and add the link of the project in this issue. Please follow the instructions and remember of assigning the students to each card.

Cheers and Happy coding!👏👏👏

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by amare1990** [comment]
Hi @leonardodiasb. We did using the steps described in [this link](https://github.com/microverseinc/curriculum-tools-copy-projects). After we used the steps described, we got the issues in the right side (in the done part) and dragged to the left side. Do you mean you should not drag the issues from the right side to the left side? Thanks for your reply.

**Comment by mckent05** [comment]
Hi @amare1990 & @leonardodiasb, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/197766970-fb5c33e6-771c-4f5f-b7eb-8b8f3d2c9fff.gif)



 ## Highlights
- I currently cannot view the Kanban board you have set up, please can you include a link to the Kanban board you setup in this issue? 🙏 🙏 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by amare1990** [comment]
Hi @mckent05. Here it is the Kanban board link.
https://github.com/users/amare1990/projects/2

**Comment by uwadonat** [comment]
Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
![awoseme](https://user-images.githubusercontent.com/65860678/197775669-f691cbfd-2537-4152-a539-a541c16a42e5.gif)


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
